# Enfermedad Dengue en la República Argentina - Aplicación de Machine Learning para su estudio y predicción de casos 
## Pre-Processing

#### Elaborado por: Fresca, Lorenzo - Mojico, Ailín- Rosselló, Matías
#### Ingeniería Industrial UTN FRBA

# CARGAR ARCHIVOS

In [1]:
#Para Colab
#from google.colab import files
#upload=files.upload()

In [2]:
pwd

'C:\\Users\\MatiRosse\\Desktop\\Ciencia de datos\\Facultad\\TP CUATRI\\TP Modificaciones'

In [3]:
ls

 El volumen de la unidad C no tiene etiqueta.
 El n£mero de serie del volumen es: 46CA-A7CB

 Directorio de C:\Users\MatiRosse\Desktop\Ciencia de datos\Facultad\TP CUATRI\TP Modificaciones

18/11/20  19:14    <DIR>          .
18/11/20  19:14    <DIR>          ..
17/11/20  14:18    <DIR>          .ipynb_checkpoints
12/11/20  00:08            66,521 Casos_Dengue_Procesados.csv
16/11/20  17:18            23,755 Casos_Dengue_Procesados_5m.csv
15/11/20  15:22            30,647 Casos_Dengue_Procesados_6m.csv
11/11/20  14:37            17,387 Casos_Dengue_Procesados_actualizado.csv
18/11/20  19:14         1,160,569 Dengue - EDA.ipynb
18/11/20  19:10           139,614 Dengue - Modelos.ipynb
17/11/20  14:23           285,736 Dengue- PreProcessing.ipynb
01/11/20  19:15           356,033 Dengue_Zika.ipynb
10/11/20  19:45           830,814 EDA casos dengue - copia.ipynb
03/10/20  11:07            65,590 estaciones_meteorologicas_provincias.csv
10/11/20  20:05         6,976,360 Exp_183015_horarios.csv
10/11/20  17:57         7,464,458 Exp_183015_horarios.xlsx
11/11/20  14:37             3,417 Exp_183015_observatorios.csv
10/11/20  19:55            83,126 Exp_183015_observatorios.xlsx
10/11/20  20:05            42,649 Exp_183015_precipitaciones.csv
10/11/20  17:57           147,456 Exp_183015_precipitaciones.xls
17/10/20  15:39                72 Untitled.ipynb
08/11/20  20:44            22,447 Untitled1.ipynb
10/11/20  20:08                72 Untitled2.ipynb
11/11/20  17:05                72 Untitled3.ipynb
11/11/20  20:40                72 Untitled4.ipynb
16/11/20  17:28                72 Untitled5.ipynb
25/09/20  12:20           107,655 vigilancia-de-dengue-y-zika_2019.csv
30/10/20  14:57            94,515 vigilancia-de-dengue-y-zika_2019_actualizado.csv
11/11/20  09:21           557,564 vigilancia-de-dengue-y-zika_2020.csv
11/11/20  09:20           364,725 vigilancia-de-dengue-y-zika_2020.xlsx
              26 archivos     18,841,398 bytes
               3 dirs  284,356,968,448 bytes libres

# IMPORTAR LIBRERÍAS

In [4]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [5]:
# Se agregó la codificación utf-8 y latin para que lea el código correctamente
dengue_18_19=pd.read_csv("vigilancia-de-dengue-y-zika_2019.csv", encoding = 'UTF-8')
dengue_20=pd.read_csv("vigilancia-de-dengue-y-zika_2020.csv", encoding = 'latin')
observatorios=pd.read_csv("Exp_183015_observatorios.csv", encoding = 'latin')
precipitaciones=pd.read_csv("Exp_183015_precipitaciones.csv", encoding = 'latin')
clima=pd.read_csv("Exp_183015_horarios.csv", encoding = 'latin')
dengue_18_19.head(20)

,departamento_id,departamento_nombre,provincia_id,provincia_nombre,año,semanas_epidemiologicas,evento_nombre,grupo_edad_id,grupo_edad_desc,cantidad_casos
0,0,*sin dato*,6,Buenos Aires,2018,11,Dengue,10,De 45 a 64 años,1.0
1,35,Avellaneda,6,Buenos Aires,2018,7,Dengue,8,De 20 a 24 años,1.0
2,35,Avellaneda,6,Buenos Aires,2018,7,Dengue,10,De 45 a 64 años,1.0
3,35,Avellaneda,6,Buenos Aires,2018,9,Dengue,6,De 10 a 14 años,1.0
4,35,Avellaneda,6,Buenos Aires,2018,9,Dengue,8,De 20 a 24 años,1.0
5,35,Avellaneda,6,Buenos Aires,2018,9,Dengue,9,De 25 a 34 años,1.0
6,35,Avellaneda,6,Buenos Aires,2018,10,Dengue,8,De 20 a 24 años,1.0
7,35,Avellaneda,6,Buenos Aires,2018,10,Dengue,10,De 45 a 64 años,1.0
8,35,Avellaneda,6,Buenos Aires,2018,11,Dengue,6,De 10 a 14 años,2.0
9,35,Avellaneda,6,Buenos Aires,2018,11,Dengue,8,De 20 a 24 años,1.0
10,35,Avellaneda,6,Buenos Aires,2018,11,Dengue,9,De 25 a 34 años,1.0
11,35,Avellaneda,6,Buenos Aires,2018,11,Dengue,10,De 45 a 64 años,1.0
12,35,Avellaneda,6,Buenos Aires,2018,12,Dengue,6,De 10 a 14 años,1.0
13,35,Avellaneda,6,Buenos Aires,2018,12,Dengue,10,De 35 a 44 años,2.0
14,35,Avellaneda,6,Buenos Aires,2018,13,Dengue,9,De 25 a 34 años,2.0
15,35,Avellaneda,6,Buenos Aires,2018,13,Dengue,10,De 35 a 44 años,2.0
16,35,Avellaneda,6,Buenos Aires,2018,13,Dengue,11,Mayor o igual de 65 años,1.0
17,35,Avellaneda,6,Buenos Aires,2018,14,Dengue,5,De 5 a 9 años,1.0
18,35,Avellaneda,6,Buenos Aires,2018,14,Dengue,6,De 10 a 14 años,2.0
19,35,Avellaneda,6,Buenos Aires,2018,14,Dengue,8,De 20 a 24 años,1.0

# LIMPIEZA CLIMA

In [6]:
#Convertimos la columna FECHA en formato fecha, y agregamos una columna "Mes" y "Año"
clima.FECHA = pd.to_datetime(clima.FECHA, dayfirst=True ) 
clima['MES'] = clima.FECHA.dt.month 
clima['AÑO'] = clima.FECHA.dt.year 
clima.head()

,ESTACION,FECHA,HORA LOCAL,TEMPERATURA (ºC),HR (%),INTENSIDAD DE VIENTO (km/h),MES,AÑO
0,10001,2018-01-01,3,9.7,94.0,0.0,1,2018
1,10001,2018-01-01,9,12.1,93.0,4.0,1,2018
2,10001,2018-01-01,15,20.4,46.0,9.0,1,2018
3,10001,2018-01-01,21,14.1,81.0,15.0,1,2018
4,10001,2018-01-02,3,10.4,89.0,4.0,1,2018

In [7]:
#Eliminamos la columna FECHA y HORA LOCAL ya que sólo filtramos por mes y año
clima  = clima.drop(['FECHA','HORA LOCAL'], axis=1)
clima

,ESTACION,TEMPERATURA (ºC),HR (%),INTENSIDAD DE VIENTO (km/h),MES,AÑO
0,10001,9.7,94.0,0.0,1,2018
1,10001,12.1,93.0,4.0,1,2018
2,10001,20.4,46.0,9.0,1,2018
3,10001,14.1,81.0,15.0,1,2018
4,10001,10.4,89.0,4.0,1,2018
...,...,...,...,...,...,...
244532,10501,8.8,87.0,19.0,6,2020
244533,10501,8.3,93.0,7.0,6,2020
244534,10501,7.2,92.0,7.0,6,2020
244535,10501,10.0,80.0,13.0,6,2020
244536,10501,6.5,94.0,2.0,6,2020

In [8]:
#Obtenido ya el mes y año, agregamos los datos de precipitaciones de cada observatorio
clima_p = pd.merge(clima, precipitaciones, left_on=["ESTACION","MES","AÑO"], right_on=["ESTACION","MES","AÑO"], how="left")
clima_p

,ESTACION,TEMPERATURA (ºC),HR (%),INTENSIDAD DE VIENTO (km/h),MES,AÑO,CANTIDAD (mm),CODIGO PRECIP
0,10001,9.7,94.0,0.0,1,2018,129.4,NaN
1,10001,12.1,93.0,4.0,1,2018,129.4,NaN
2,10001,20.4,46.0,9.0,1,2018,129.4,NaN
3,10001,14.1,81.0,15.0,1,2018,129.4,NaN
4,10001,10.4,89.0,4.0,1,2018,129.4,NaN
...,...,...,...,...,...,...,...,...
244532,10501,8.8,87.0,19.0,6,2020,12.0,NaN
244533,10501,8.3,93.0,7.0,6,2020,12.0,NaN
244534,10501,7.2,92.0,7.0,6,2020,12.0,NaN
244535,10501,10.0,80.0,13.0,6,2020,12.0,NaN
244536,10501,6.5,94.0,2.0,6,2020,12.0,NaN

In [9]:
clima_p.rename(columns={'CANTIDAD (mm)':'PRECIPITACION (mm)'}, inplace=True)

#Eliminamos la columna CODIGO PRECIP que no es de interés
clima_p= clima_p.drop('CODIGO PRECIP', axis=1)
clima_p

,ESTACION,TEMPERATURA (ºC),HR (%),INTENSIDAD DE VIENTO (km/h),MES,AÑO,PRECIPITACION (mm)
0,10001,9.7,94.0,0.0,1,2018,129.4
1,10001,12.1,93.0,4.0,1,2018,129.4
2,10001,20.4,46.0,9.0,1,2018,129.4
3,10001,14.1,81.0,15.0,1,2018,129.4
4,10001,10.4,89.0,4.0,1,2018,129.4
...,...,...,...,...,...,...,...
244532,10501,8.8,87.0,19.0,6,2020,12.0
244533,10501,8.3,93.0,7.0,6,2020,12.0
244534,10501,7.2,92.0,7.0,6,2020,12.0
244535,10501,10.0,80.0,13.0,6,2020,12.0
244536,10501,6.5,94.0,2.0,6,2020,12.0

In [10]:
#Verificamos si existen registros nulos
col_NaN1 = clima.isnull().any()
col_NaN1

ESTACION                       False
TEMPERATURA (ºC)                True
HR (%)                          True
INTENSIDAD DE VIENTO (km/h)     True
MES                            False
AÑO                            False
dtype: bool

In [11]:
#Contamos cuantos registros nulos hay por variable
col_NaN1 = clima.isnull().sum()
col_NaN1

ESTACION                         0
TEMPERATURA (ºC)                55
HR (%)                         108
INTENSIDAD DE VIENTO (km/h)     16
MES                              0
AÑO                              0
dtype: int64

In [12]:
#Eliminamos los registros con valores nulos
clima.dropna(how ='any', inplace = True)
np.shape(clima)
print(f'Nuestro dataset luego de la limpieza tiene {clima.shape[0]} filas y {clima.shape[1]} columnas.')

Nuestro dataset luego de la limpieza tiene 244416 filas y 6 columnas.

In [13]:
#Agregamos a qué provincia pertenece cada observatorio con el listado de observatorios
clima_obs = pd.merge(clima_p, observatorios, left_on="ESTACION", right_on="ESTACION", how="inner")
clima_obs

,ESTACION,TEMPERATURA (ºC),HR (%),INTENSIDAD DE VIENTO (km/h),MES,AÑO,PRECIPITACION (mm),NOMBRE,PROVINCIA,LATITUD (º.minutos),LONGITUD (º.minutos),ALTURA (m)
0,10001,9.7,94.0,0.0,1,2018,129.4,LA QUIACA OBSERVATORIO,JUJUY,22.06,65.36,"3,459"
1,10001,12.1,93.0,4.0,1,2018,129.4,LA QUIACA OBSERVATORIO,JUJUY,22.06,65.36,"3,459"
2,10001,20.4,46.0,9.0,1,2018,129.4,LA QUIACA OBSERVATORIO,JUJUY,22.06,65.36,"3,459"
3,10001,14.1,81.0,15.0,1,2018,129.4,LA QUIACA OBSERVATORIO,JUJUY,22.06,65.36,"3,459"
4,10001,10.4,89.0,4.0,1,2018,129.4,LA QUIACA OBSERVATORIO,JUJUY,22.06,65.36,"3,459"
...,...,...,...,...,...,...,...,...,...,...,...,...
244532,10501,8.8,87.0,19.0,6,2020,12.0,VIEDMA AERO,RÍO NEGRO,40.51,63.01,7
244533,10501,8.3,93.0,7.0,6,2020,12.0,VIEDMA AERO,RÍO NEGRO,40.51,63.01,7
244534,10501,7.2,92.0,7.0,6,2020,12.0,VIEDMA AERO,RÍO NEGRO,40.51,63.01,7
244535,10501,10.0,80.0,13.0,6,2020,12.0,VIEDMA AERO,RÍO NEGRO,40.51,63.01,7
244536,10501,6.5,94.0,2.0,6,2020,12.0,VIEDMA AERO,RÍO NEGRO,40.51,63.01,7

In [14]:
#Verificamos si todavía tenemos las 25 provincias.
np.unique(clima_obs.PROVINCIA)
np.unique(clima_obs.PROVINCIA).shape
print(f'En nuestro dataset luego de limpiar los nulos hay {np.unique(clima_obs.PROVINCIA).shape[0]} provincias distintas')

En nuestro dataset luego de limpiar los nulos hay 25 provincias distintas

In [15]:
clima_obs=clima_obs.loc[:, ['PROVINCIA', 'MES','AÑO','TEMPERATURA (ºC)','PRECIPITACION (mm)','HR (%)','INTENSIDAD DE VIENTO (km/h)']]
clima_obs

,PROVINCIA,MES,AÑO,TEMPERATURA (ºC),PRECIPITACION (mm),HR (%),INTENSIDAD DE VIENTO (km/h)
0,JUJUY,1,2018,9.7,129.4,94.0,0.0
1,JUJUY,1,2018,12.1,129.4,93.0,4.0
2,JUJUY,1,2018,20.4,129.4,46.0,9.0
3,JUJUY,1,2018,14.1,129.4,81.0,15.0
4,JUJUY,1,2018,10.4,129.4,89.0,4.0
...,...,...,...,...,...,...,...
244532,RÍO NEGRO,6,2020,8.8,12.0,87.0,19.0
244533,RÍO NEGRO,6,2020,8.3,12.0,93.0,7.0
244534,RÍO NEGRO,6,2020,7.2,12.0,92.0,7.0
244535,RÍO NEGRO,6,2020,10.0,12.0,80.0,13.0
244536,RÍO NEGRO,6,2020,6.5,12.0,94.0,2.0

In [16]:
#Buscamos las condiciones medias por mes de cada provincia en cada año
clima_obs=clima_obs.groupby(['PROVINCIA','MES','AÑO'], as_index=True ).mean()
clima_obs

                       TEMPERATURA (ºC)  PRECIPITACION (mm)     HR (%)  \
PROVINCIA    MES AÑO
BUENOS AIRES 1   2018         23.818903           78.826000  59.146452
                 2019         22.901084          131.553399  69.955962
                 2020         22.715584           79.471401  62.084416
             2   2018         23.143357           49.372000  62.202143
                 2019         21.580357           60.700000  66.137143
...                                 ...                 ...        ...
USHUAIA      10  2019          6.205645           47.900000  66.177419
             11  2018          8.048333           23.500000  61.933333
                 2019          7.395833           50.100000  71.591667
             12  2018          9.560484           24.200000  63.362903
                 2019          9.342742           39.800000  67.120968

                       INTENSIDAD DE VIENTO (km/h)
PROVINCIA    MES AÑO
BUENOS AIRES 1   2018                    14.287097
                 2019                    14.790099
                 2020                    15.177807
             2   2018                    13.391429
                 2019                    12.844286
...                                            ...
USHUAIA      10  2019                    28.225806
             11  2018                    30.483333
                 2019                    22.641667
             12  2018                    25.620968
                 2019                    25.290323

[750 rows x 4 columns]

In [17]:
clima_obs=clima_obs.reset_index()

In [18]:
clima_obs

,PROVINCIA,MES,AÑO,TEMPERATURA (ºC),PRECIPITACION (mm),HR (%),INTENSIDAD DE VIENTO (km/h)
0,BUENOS AIRES,1,2018,23.818903,78.826000,59.146452,14.287097
1,BUENOS AIRES,1,2019,22.901084,131.553399,69.955962,14.790099
2,BUENOS AIRES,1,2020,22.715584,79.471401,62.084416,15.177807
3,BUENOS AIRES,2,2018,23.143357,49.372000,62.202143,13.391429
4,BUENOS AIRES,2,2019,21.580357,60.700000,66.137143,12.844286
...,...,...,...,...,...,...,...
745,USHUAIA,10,2019,6.205645,47.900000,66.177419,28.225806
746,USHUAIA,11,2018,8.048333,23.500000,61.933333,30.483333
747,USHUAIA,11,2019,7.395833,50.100000,71.591667,22.641667
748,USHUAIA,12,2018,9.560484,24.200000,63.362903,25.620968
749,USHUAIA,12,2019,9.342742,39.800000,67.120968,25.290323

# LIMPIEZA DENGUE DATAFRAME

In [19]:
dengue_18_19.head(20)

,departamento_id,departamento_nombre,provincia_id,provincia_nombre,año,semanas_epidemiologicas,evento_nombre,grupo_edad_id,grupo_edad_desc,cantidad_casos
0,0,*sin dato*,6,Buenos Aires,2018,11,Dengue,10,De 45 a 64 años,1.0
1,35,Avellaneda,6,Buenos Aires,2018,7,Dengue,8,De 20 a 24 años,1.0
2,35,Avellaneda,6,Buenos Aires,2018,7,Dengue,10,De 45 a 64 años,1.0
3,35,Avellaneda,6,Buenos Aires,2018,9,Dengue,6,De 10 a 14 años,1.0
4,35,Avellaneda,6,Buenos Aires,2018,9,Dengue,8,De 20 a 24 años,1.0
5,35,Avellaneda,6,Buenos Aires,2018,9,Dengue,9,De 25 a 34 años,1.0
6,35,Avellaneda,6,Buenos Aires,2018,10,Dengue,8,De 20 a 24 años,1.0
7,35,Avellaneda,6,Buenos Aires,2018,10,Dengue,10,De 45 a 64 años,1.0
8,35,Avellaneda,6,Buenos Aires,2018,11,Dengue,6,De 10 a 14 años,2.0
9,35,Avellaneda,6,Buenos Aires,2018,11,Dengue,8,De 20 a 24 años,1.0
10,35,Avellaneda,6,Buenos Aires,2018,11,Dengue,9,De 25 a 34 años,1.0
11,35,Avellaneda,6,Buenos Aires,2018,11,Dengue,10,De 45 a 64 años,1.0
12,35,Avellaneda,6,Buenos Aires,2018,12,Dengue,6,De 10 a 14 años,1.0
13,35,Avellaneda,6,Buenos Aires,2018,12,Dengue,10,De 35 a 44 años,2.0
14,35,Avellaneda,6,Buenos Aires,2018,13,Dengue,9,De 25 a 34 años,2.0
15,35,Avellaneda,6,Buenos Aires,2018,13,Dengue,10,De 35 a 44 años,2.0
16,35,Avellaneda,6,Buenos Aires,2018,13,Dengue,11,Mayor o igual de 65 años,1.0
17,35,Avellaneda,6,Buenos Aires,2018,14,Dengue,5,De 5 a 9 años,1.0
18,35,Avellaneda,6,Buenos Aires,2018,14,Dengue,6,De 10 a 14 años,2.0
19,35,Avellaneda,6,Buenos Aires,2018,14,Dengue,8,De 20 a 24 años,1.0

In [20]:
dengue_20.head()

,departamento_id,departamento_nombre,provincia_id,provincia_nombre,anio,semanas_epidemiologicas,evento_nombre,grupo_edad_id,grupo_edad_desc,cantidad_casos
0,1,COMUNA 1,2,CABA,2020,1,Dengue,6,De 10 a 14 años,1
1,1,COMUNA 1,2,CABA,2020,2,Dengue,6,De 10 a 14 años,1
2,1,COMUNA 1,2,CABA,2020,3,Dengue,9,De 25 a 34 años,1
3,1,COMUNA 1,2,CABA,2020,3,Dengue,11,De 45 a 65 años,1
4,1,COMUNA 1,2,CABA,2020,4,Dengue,9,De 25 a 34 años,1

In [21]:
#Observamos que ambas tienen las mismas columnas, pero tenemos que renombrar anio para poder unirlas
dengue_20.rename(columns={'anio':'año'}, inplace=True)
dengue_20

,departamento_id,departamento_nombre,provincia_id,provincia_nombre,año,semanas_epidemiologicas,evento_nombre,grupo_edad_id,grupo_edad_desc,cantidad_casos
0,1,COMUNA 1,2,CABA,2020,1,Dengue,6,De 10 a 14 años,1
1,1,COMUNA 1,2,CABA,2020,2,Dengue,6,De 10 a 14 años,1
2,1,COMUNA 1,2,CABA,2020,3,Dengue,9,De 25 a 34 años,1
3,1,COMUNA 1,2,CABA,2020,3,Dengue,11,De 45 a 65 años,1
4,1,COMUNA 1,2,CABA,2020,4,Dengue,9,De 25 a 34 años,1
...,...,...,...,...,...,...,...,...,...,...
8998,63,GENERAL GUEMES,22,Chaco,2020,18,Dengue,5,De 5 a 9 años,2
8999,63,GENERAL GUEMES,22,Chaco,2020,20,Dengue,8,De 20 a 24 años,3
9000,63,GENERAL GUEMES,22,Chaco,2020,23,Dengue,9,De 25 a 34 años,1
9001,63,GENERAL GUEMES,22,Chaco,2020,23,Dengue,11,De 45 a 65 años,1
9002,84,LIBERTADOR GENERAL SAN MARTIN,22,Chaco,2020,11,Dengue,9,De 25 a 34 años,1

In [22]:
dengue = pd.concat([dengue_18_19,dengue_20], axis=0)
dengue

,departamento_id,departamento_nombre,provincia_id,provincia_nombre,año,semanas_epidemiologicas,evento_nombre,grupo_edad_id,grupo_edad_desc,cantidad_casos
0,0,*sin dato*,6,Buenos Aires,2018,11,Dengue,10,De 45 a 64 años,1.0
1,35,Avellaneda,6,Buenos Aires,2018,7,Dengue,8,De 20 a 24 años,1.0
2,35,Avellaneda,6,Buenos Aires,2018,7,Dengue,10,De 45 a 64 años,1.0
3,35,Avellaneda,6,Buenos Aires,2018,9,Dengue,6,De 10 a 14 años,1.0
4,35,Avellaneda,6,Buenos Aires,2018,9,Dengue,8,De 20 a 24 años,1.0
...,...,...,...,...,...,...,...,...,...,...
8998,63,GENERAL GUEMES,22,Chaco,2020,18,Dengue,5,De 5 a 9 años,2.0
8999,63,GENERAL GUEMES,22,Chaco,2020,20,Dengue,8,De 20 a 24 años,3.0
9000,63,GENERAL GUEMES,22,Chaco,2020,23,Dengue,9,De 25 a 34 años,1.0
9001,63,GENERAL GUEMES,22,Chaco,2020,23,Dengue,11,De 45 a 65 años,1.0
9002,84,LIBERTADOR GENERAL SAN MARTIN,22,Chaco,2020,11,Dengue,9,De 25 a 34 años,1.0

In [23]:
np.shape(dengue)
print(f'Nuestro dataset tiene {dengue.shape[0]} registros y {dengue.shape[1]} columnas.')

Nuestro dataset tiene 10489 registros y 10 columnas.

In [24]:
dengue['departamento_nombre'].replace('*sin dato*', np.nan, inplace = True )
dengue.head()

,departamento_id,departamento_nombre,provincia_id,provincia_nombre,año,semanas_epidemiologicas,evento_nombre,grupo_edad_id,grupo_edad_desc,cantidad_casos
0,0,NaN,6,Buenos Aires,2018,11,Dengue,10,De 45 a 64 años,1.0
1,35,Avellaneda,6,Buenos Aires,2018,7,Dengue,8,De 20 a 24 años,1.0
2,35,Avellaneda,6,Buenos Aires,2018,7,Dengue,10,De 45 a 64 años,1.0
3,35,Avellaneda,6,Buenos Aires,2018,9,Dengue,6,De 10 a 14 años,1.0
4,35,Avellaneda,6,Buenos Aires,2018,9,Dengue,8,De 20 a 24 años,1.0

In [25]:
#Verificamos si existen registros nulos. Vemos que sólo existen en departamento y cantidad de casos.
#No se eliminarán debido no nos interesa el departamento, y los nulos en cantidad de casos se reemplazarán por 0.
col_NaN = dengue.isnull().any()
col_NaN

departamento_id            False
departamento_nombre         True
provincia_id               False
provincia_nombre           False
año                        False
semanas_epidemiologicas    False
evento_nombre              False
grupo_edad_id              False
grupo_edad_desc            False
cantidad_casos              True
dtype: bool

In [26]:
#Eliminamos en caso de que hayan duplicados
dengue.drop_duplicates()

,departamento_id,departamento_nombre,provincia_id,provincia_nombre,año,semanas_epidemiologicas,evento_nombre,grupo_edad_id,grupo_edad_desc,cantidad_casos
0,0,NaN,6,Buenos Aires,2018,11,Dengue,10,De 45 a 64 años,1.0
1,35,Avellaneda,6,Buenos Aires,2018,7,Dengue,8,De 20 a 24 años,1.0
2,35,Avellaneda,6,Buenos Aires,2018,7,Dengue,10,De 45 a 64 años,1.0
3,35,Avellaneda,6,Buenos Aires,2018,9,Dengue,6,De 10 a 14 años,1.0
4,35,Avellaneda,6,Buenos Aires,2018,9,Dengue,8,De 20 a 24 años,1.0
...,...,...,...,...,...,...,...,...,...,...
8998,63,GENERAL GUEMES,22,Chaco,2020,18,Dengue,5,De 5 a 9 años,2.0
8999,63,GENERAL GUEMES,22,Chaco,2020,20,Dengue,8,De 20 a 24 años,3.0
9000,63,GENERAL GUEMES,22,Chaco,2020,23,Dengue,9,De 25 a 34 años,1.0
9001,63,GENERAL GUEMES,22,Chaco,2020,23,Dengue,11,De 45 a 65 años,1.0
9002,84,LIBERTADOR GENERAL SAN MARTIN,22,Chaco,2020,11,Dengue,9,De 25 a 34 años,1.0

In [27]:
#Vamos a crear un brand de meses según la semana epidemológica para ubicarlo en el mes.
dengue.loc[(dengue['semanas_epidemiologicas'] > 0) & (dengue['semanas_epidemiologicas'] <= 5), 'Mes'] = 1
dengue.loc[(dengue['semanas_epidemiologicas'] > 5) & (dengue['semanas_epidemiologicas'] <= 9 ), 'Mes'] = 2
dengue.loc[(dengue['semanas_epidemiologicas'] > 9) & (dengue['semanas_epidemiologicas'] <= 14), 'Mes'] = 3
dengue.loc[(dengue['semanas_epidemiologicas'] > 14) & (dengue['semanas_epidemiologicas'] <= 18), 'Mes'] = 4
dengue.loc[(dengue['semanas_epidemiologicas'] > 18) & (dengue['semanas_epidemiologicas'] <= 23), 'Mes'] = 5
dengue.loc[(dengue['semanas_epidemiologicas'] > 23) & (dengue['semanas_epidemiologicas'] <= 27), 'Mes'] = 6
dengue.loc[(dengue['semanas_epidemiologicas'] > 27) & (dengue['semanas_epidemiologicas'] <= 31), 'Mes'] = 7
dengue.loc[(dengue['semanas_epidemiologicas'] > 31) & (dengue['semanas_epidemiologicas'] <= 36), 'Mes'] = 8
dengue.loc[(dengue['semanas_epidemiologicas'] > 36) & (dengue['semanas_epidemiologicas'] <= 40), 'Mes'] = 9
dengue.loc[(dengue['semanas_epidemiologicas'] > 40) & (dengue['semanas_epidemiologicas'] <= 44), 'Mes'] = 10
dengue.loc[(dengue['semanas_epidemiologicas'] > 44) & (dengue['semanas_epidemiologicas'] <= 49), 'Mes'] = 11
dengue.loc[(dengue['semanas_epidemiologicas'] > 50) & (dengue['semanas_epidemiologicas'] <= 53), 'Mes'] = 12

dengue=dengue.sort_values(['semanas_epidemiologicas'], ascending=[True])
dengue.head()

,departamento_id,departamento_nombre,provincia_id,provincia_nombre,año,semanas_epidemiologicas,evento_nombre,grupo_edad_id,grupo_edad_desc,cantidad_casos,Mes
1343,11,COMUNA 11,2,CABA,2020,1,Dengue,10,De 35 a 44 años,1.0,1.0
2393,21,Capital,18,Corrientes,2020,1,Dengue,12,Mayores de 65 años,1.0,1.0
2014,14,Formosa,34,Formosa,2020,1,Dengue,10,De 35 a 44 años,2.0,1.0
2015,14,Formosa,34,Formosa,2020,1,Dengue,11,De 45 a 65 años,3.0,1.0
2392,21,Capital,18,Corrientes,2020,1,Dengue,11,De 45 a 65 años,1.0,1.0

In [28]:
dengue=dengue.drop(['departamento_nombre','departamento_id','provincia_id','semanas_epidemiologicas','evento_nombre','grupo_edad_id','grupo_edad_desc'], axis=1)
dengue.head(20)

     provincia_nombre   año  cantidad_casos  Mes
1343             CABA  2020             1.0  1.0
2393       Corrientes  2020             1.0  1.0
2014          Formosa  2020             2.0  1.0
2015          Formosa  2020             3.0  1.0
2392       Corrientes  2020             1.0  1.0
95               CABA  2020             1.0  1.0
5898         Santa Fe  2020             1.0  1.0
4700       Entre Ríos  2020             1.0  1.0
454           Formosa  2018             3.0  1.0
0                CABA  2020             1.0  1.0
4186         Misiones  2020             2.0  1.0
4185         Misiones  2020             8.0  1.0
4184         Misiones  2020             1.0  1.0
4183         Misiones  2020             5.0  1.0
4182         Misiones  2020             7.0  1.0
5801       Entre Ríos  2020             1.0  1.0
4181         Misiones  2020             4.0  1.0
4179         Misiones  2020             2.0  1.0
350              CABA  2020             1.0  1.0
349              CABA  2020             1.0  1.0

In [29]:
#Realizamos una agrupación para poder obtener la cantidad de casos totales en cada provincia en cada mes
dengue=dengue.groupby(['provincia_nombre','Mes','año'], as_index=True ).sum()
dengue.head(50)

                            cantidad_casos
provincia_nombre Mes  año
Buenos Aires     1.0  2020           103.0
                 2.0  2018             9.0
                      2019             7.0
                      2020           426.0
                 3.0  2018            70.0
                      2019            30.0
                      2020          2377.0
                 4.0  2018            59.0
                      2019            12.0
                      2020          1319.0
                 5.0  2018            15.0
                      2019             3.0
                      2020           338.0
                 6.0  2020            11.0
                 7.0  2020             1.0
                 8.0  2020             1.0
                 9.0  2020             4.0
                 10.0 2020             1.0
CABA             1.0  2019             2.0
                      2020           162.0
                 2.0  2018            10.0
                      2019             3.0
                      2020           911.0
                 3.0  2018            38.0
                      2019             6.0
                      2020          4681.0
                 4.0  2018            56.0
                      2019            12.0
                      2020          2816.0
                 5.0  2018             6.0
                      2019             2.0
                      2020           594.0
                 6.0  2018             1.0
                      2019             1.0
                      2020             8.0
                 7.0  2020             3.0
                 9.0  2020             1.0
                 10.0 2020             1.0
Catamarca        2.0  2020            17.0
                 3.0  2020           213.0
                 4.0  2020            84.0
                 5.0  2020            23.0
Chaco            1.0  2018             1.0
                      2020            19.0
                 2.0  2020           192.0
                 3.0  2018            40.0
                      2019             5.0
                      2020          1016.0
                 4.0  2018           229.0
                      2019            10.0

In [30]:
dengue=dengue.reset_index()

In [31]:
dengue.head(40)

   provincia_nombre   Mes   año  cantidad_casos
0      Buenos Aires   1.0  2020           103.0
1      Buenos Aires   2.0  2018             9.0
2      Buenos Aires   2.0  2019             7.0
3      Buenos Aires   2.0  2020           426.0
4      Buenos Aires   3.0  2018            70.0
5      Buenos Aires   3.0  2019            30.0
6      Buenos Aires   3.0  2020          2377.0
7      Buenos Aires   4.0  2018            59.0
8      Buenos Aires   4.0  2019            12.0
9      Buenos Aires   4.0  2020          1319.0
10     Buenos Aires   5.0  2018            15.0
11     Buenos Aires   5.0  2019             3.0
12     Buenos Aires   5.0  2020           338.0
13     Buenos Aires   6.0  2020            11.0
14     Buenos Aires   7.0  2020             1.0
15     Buenos Aires   8.0  2020             1.0
16     Buenos Aires   9.0  2020             4.0
17     Buenos Aires  10.0  2020             1.0
18             CABA   1.0  2019             2.0
19             CABA   1.0  2020           162.0
20             CABA   2.0  2018            10.0
21             CABA   2.0  2019             3.0
22             CABA   2.0  2020           911.0
23             CABA   3.0  2018            38.0
24             CABA   3.0  2019             6.0
25             CABA   3.0  2020          4681.0
26             CABA   4.0  2018            56.0
27             CABA   4.0  2019            12.0
28             CABA   4.0  2020          2816.0
29             CABA   5.0  2018             6.0
30             CABA   5.0  2019             2.0
31             CABA   5.0  2020           594.0
32             CABA   6.0  2018             1.0
33             CABA   6.0  2019             1.0
34             CABA   6.0  2020             8.0
35             CABA   7.0  2020             3.0
36             CABA   9.0  2020             1.0
37             CABA  10.0  2020             1.0
38        Catamarca   2.0  2020            17.0
39        Catamarca   3.0  2020           213.0

In [32]:
clima_obs

,PROVINCIA,MES,AÑO,TEMPERATURA (ºC),PRECIPITACION (mm),HR (%),INTENSIDAD DE VIENTO (km/h)
0,BUENOS AIRES,1,2018,23.818903,78.826000,59.146452,14.287097
1,BUENOS AIRES,1,2019,22.901084,131.553399,69.955962,14.790099
2,BUENOS AIRES,1,2020,22.715584,79.471401,62.084416,15.177807
3,BUENOS AIRES,2,2018,23.143357,49.372000,62.202143,13.391429
4,BUENOS AIRES,2,2019,21.580357,60.700000,66.137143,12.844286
...,...,...,...,...,...,...,...
745,USHUAIA,10,2019,6.205645,47.900000,66.177419,28.225806
746,USHUAIA,11,2018,8.048333,23.500000,61.933333,30.483333
747,USHUAIA,11,2019,7.395833,50.100000,71.591667,22.641667
748,USHUAIA,12,2018,9.560484,24.200000,63.362903,25.620968
749,USHUAIA,12,2019,9.342742,39.800000,67.120968,25.290323

# UNION DENGUE Y CLIMA

In [33]:
#Observamos la diferencia entre minúsculas y mayúsculas entre ambos dataframes a concatenar
#Por lo tanto vamos a modificar el formato del dengue, pasandolo todo a mayúscula
dengue.tail(20)

        provincia_nombre  Mes   año  cantidad_casos
190  Santiago del Estero  1.0  2018             2.0
191  Santiago del Estero  1.0  2019             1.0
192  Santiago del Estero  1.0  2020             2.0
193  Santiago del Estero  2.0  2020            35.0
194  Santiago del Estero  3.0  2019             1.0
195  Santiago del Estero  3.0  2020            15.0
196  Santiago del Estero  4.0  2018            46.0
197  Santiago del Estero  4.0  2019             1.0
198  Santiago del Estero  4.0  2020            41.0
199  Santiago del Estero  5.0  2018           145.0
200  Santiago del Estero  5.0  2020            69.0
201  Santiago del Estero  6.0  2018             1.0
202     Tierra del Fuego  3.0  2020             1.0
203              Tucumán  2.0  2020             2.0
204              Tucumán  3.0  2018             1.0
205              Tucumán  3.0  2019             1.0
206              Tucumán  3.0  2020           765.0
207              Tucumán  4.0  2020           186.0
208              Tucumán  5.0  2018             1.0
209              Tucumán  5.0  2020          6803.0

In [34]:
dengue["provincia_nombre"] = dengue["provincia_nombre"].apply(lambda name : name.upper())
dengue

    provincia_nombre  Mes   año  cantidad_casos
0       BUENOS AIRES  1.0  2020           103.0
1       BUENOS AIRES  2.0  2018             9.0
2       BUENOS AIRES  2.0  2019             7.0
3       BUENOS AIRES  2.0  2020           426.0
4       BUENOS AIRES  3.0  2018            70.0
..               ...  ...   ...             ...
205          TUCUMÁN  3.0  2019             1.0
206          TUCUMÁN  3.0  2020           765.0
207          TUCUMÁN  4.0  2020           186.0
208          TUCUMÁN  5.0  2018             1.0
209          TUCUMÁN  5.0  2020          6803.0

[210 rows x 4 columns]

In [35]:
casos = pd.merge(clima_obs, dengue, left_on=['PROVINCIA','MES','AÑO'], right_on=['provincia_nombre','Mes','año'], how="left")
casos.head(20)

,PROVINCIA,MES,AÑO,TEMPERATURA (ºC),PRECIPITACION (mm),HR (%),INTENSIDAD DE VIENTO (km/h),provincia_nombre,Mes,año,cantidad_casos
0,BUENOS AIRES,1,2018,23.818903,78.826000,59.146452,14.287097,NaN,NaN,NaN,NaN
1,BUENOS AIRES,1,2019,22.901084,131.553399,69.955962,14.790099,NaN,NaN,NaN,NaN
2,BUENOS AIRES,1,2020,22.715584,79.471401,62.084416,15.177807,BUENOS AIRES,1.0,2020.0,103.0
3,BUENOS AIRES,2,2018,23.143357,49.372000,62.202143,13.391429,BUENOS AIRES,2.0,2018.0,9.0
4,BUENOS AIRES,2,2019,21.580357,60.700000,66.137143,12.844286,BUENOS AIRES,2.0,2019.0,7.0
5,BUENOS AIRES,2,2020,21.921123,87.724632,66.459270,14.743680,BUENOS AIRES,2.0,2020.0,426.0
6,BUENOS AIRES,3,2018,19.504000,69.082000,64.185161,13.586452,BUENOS AIRES,3.0,2018.0,70.0
7,BUENOS AIRES,3,2019,18.507166,99.188702,74.474500,13.205939,BUENOS AIRES,3.0,2019.0,30.0
8,BUENOS AIRES,3,2020,21.853557,155.041634,73.155468,13.345191,BUENOS AIRES,3.0,2020.0,2377.0
9,BUENOS AIRES,4,2018,18.621348,141.735824,78.769179,12.490994,BUENOS AIRES,4.0,2018.0,59.0
10,BUENOS AIRES,4,2019,16.302600,44.530000,73.969333,11.300000,BUENOS AIRES,4.0,2019.0,12.0
11,BUENOS AIRES,4,2020,15.744112,107.766712,76.163376,13.279101,BUENOS AIRES,4.0,2020.0,1319.0
12,BUENOS AIRES,5,2018,13.449032,117.732000,83.012258,11.156774,BUENOS AIRES,5.0,2018.0,15.0
13,BUENOS AIRES,5,2019,12.482000,54.382000,79.051613,12.054839,BUENOS AIRES,5.0,2019.0,3.0
14,BUENOS AIRES,5,2020,12.536700,17.883718,76.064069,14.178878,BUENOS AIRES,5.0,2020.0,338.0
15,BUENOS AIRES,6,2018,8.231733,13.326000,75.712667,12.865333,NaN,NaN,NaN,NaN
16,BUENOS AIRES,6,2019,11.143667,102.586000,81.225333,13.998000,NaN,NaN,NaN,NaN
17,BUENOS AIRES,6,2020,9.753102,63.969393,80.034106,12.358555,BUENOS AIRES,6.0,2020.0,11.0
18,BUENOS AIRES,7,2018,8.098323,67.104000,82.154839,13.823871,NaN,NaN,NaN,NaN
19,BUENOS AIRES,7,2019,8.322754,34.790821,76.181759,11.975436,NaN,NaN,NaN,NaN

In [36]:
casos.drop(columns=["provincia_nombre","Mes","año"], inplace=True)
casos.head(20)

,PROVINCIA,MES,AÑO,TEMPERATURA (ºC),PRECIPITACION (mm),HR (%),INTENSIDAD DE VIENTO (km/h),cantidad_casos
0,BUENOS AIRES,1,2018,23.818903,78.826000,59.146452,14.287097,NaN
1,BUENOS AIRES,1,2019,22.901084,131.553399,69.955962,14.790099,NaN
2,BUENOS AIRES,1,2020,22.715584,79.471401,62.084416,15.177807,103.0
3,BUENOS AIRES,2,2018,23.143357,49.372000,62.202143,13.391429,9.0
4,BUENOS AIRES,2,2019,21.580357,60.700000,66.137143,12.844286,7.0
5,BUENOS AIRES,2,2020,21.921123,87.724632,66.459270,14.743680,426.0
6,BUENOS AIRES,3,2018,19.504000,69.082000,64.185161,13.586452,70.0
7,BUENOS AIRES,3,2019,18.507166,99.188702,74.474500,13.205939,30.0
8,BUENOS AIRES,3,2020,21.853557,155.041634,73.155468,13.345191,2377.0
9,BUENOS AIRES,4,2018,18.621348,141.735824,78.769179,12.490994,59.0
10,BUENOS AIRES,4,2019,16.302600,44.530000,73.969333,11.300000,12.0
11,BUENOS AIRES,4,2020,15.744112,107.766712,76.163376,13.279101,1319.0
12,BUENOS AIRES,5,2018,13.449032,117.732000,83.012258,11.156774,15.0
13,BUENOS AIRES,5,2019,12.482000,54.382000,79.051613,12.054839,3.0
14,BUENOS AIRES,5,2020,12.536700,17.883718,76.064069,14.178878,338.0
15,BUENOS AIRES,6,2018,8.231733,13.326000,75.712667,12.865333,NaN
16,BUENOS AIRES,6,2019,11.143667,102.586000,81.225333,13.998000,NaN
17,BUENOS AIRES,6,2020,9.753102,63.969393,80.034106,12.358555,11.0
18,BUENOS AIRES,7,2018,8.098323,67.104000,82.154839,13.823871,NaN
19,BUENOS AIRES,7,2019,8.322754,34.790821,76.181759,11.975436,NaN

In [37]:
#Una vez que logrado hacer la unión, reemplazamos los NaN por 0, que serían las provincias que no tuvieron casos en un mes determinado.
casos.fillna(0, inplace=True)
casos.head(50)

,PROVINCIA,MES,AÑO,TEMPERATURA (ºC),PRECIPITACION (mm),HR (%),INTENSIDAD DE VIENTO (km/h),cantidad_casos
0,BUENOS AIRES,1,2018,23.818903,78.826000,59.146452,14.287097,0.0
1,BUENOS AIRES,1,2019,22.901084,131.553399,69.955962,14.790099,0.0
2,BUENOS AIRES,1,2020,22.715584,79.471401,62.084416,15.177807,103.0
3,BUENOS AIRES,2,2018,23.143357,49.372000,62.202143,13.391429,9.0
4,BUENOS AIRES,2,2019,21.580357,60.700000,66.137143,12.844286,7.0
5,BUENOS AIRES,2,2020,21.921123,87.724632,66.459270,14.743680,426.0
6,BUENOS AIRES,3,2018,19.504000,69.082000,64.185161,13.586452,70.0
7,BUENOS AIRES,3,2019,18.507166,99.188702,74.474500,13.205939,30.0
8,BUENOS AIRES,3,2020,21.853557,155.041634,73.155468,13.345191,2377.0
9,BUENOS AIRES,4,2018,18.621348,141.735824,78.769179,12.490994,59.0
10,BUENOS AIRES,4,2019,16.302600,44.530000,73.969333,11.300000,12.0
11,BUENOS AIRES,4,2020,15.744112,107.766712,76.163376,13.279101,1319.0
12,BUENOS AIRES,5,2018,13.449032,117.732000,83.012258,11.156774,15.0
13,BUENOS AIRES,5,2019,12.482000,54.382000,79.051613,12.054839,3.0
14,BUENOS AIRES,5,2020,12.536700,17.883718,76.064069,14.178878,338.0
15,BUENOS AIRES,6,2018,8.231733,13.326000,75.712667,12.865333,0.0
16,BUENOS AIRES,6,2019,11.143667,102.586000,81.225333,13.998000,0.0
17,BUENOS AIRES,6,2020,9.753102,63.969393,80.034106,12.358555,11.0
18,BUENOS AIRES,7,2018,8.098323,67.104000,82.154839,13.823871,0.0
19,BUENOS AIRES,7,2019,8.322754,34.790821,76.181759,11.975436,0.0
20,BUENOS AIRES,8,2018,9.790645,38.502000,74.400645,15.110968,0.0
21,BUENOS AIRES,8,2019,9.667311,13.834558,68.372018,13.231464,0.0
22,BUENOS AIRES,9,2018,14.295133,107.376000,75.001333,14.029333,0.0
23,BUENOS AIRES,9,2019,12.372933,29.706000,63.532000,15.346667,0.0
24,BUENOS AIRES,10,2018,15.258870,44.204074,69.678055,14.205650,0.0
25,BUENOS AIRES,10,2019,15.241742,112.102000,67.305806,15.910323,0.0
26,BUENOS AIRES,11,2018,18.957123,139.897751,68.382413,15.964554,0.0
27,BUENOS AIRES,11,2019,20.204733,55.152000,62.044667,15.905333,0.0
28,BUENOS AIRES,12,2018,21.134901,142.385242,63.023179,15.547981,0.0
29,BUENOS AIRES,12,2019,21.684645,88.658000,58.165161,15.627097,0.0
30,CABA,1,2018,25.350806,35.300000,61.604839,12.500000,0.0
31,CABA,1,2019,24.774194,145.750000,70.608871,11.963710,2.0
32,CABA,1,2020,24.758468,66.150000,61.419355,12.153226,162.0
33,CABA,2,2018,24.606250,42.150000,63.611607,12.486607,10.0
34,CABA,2,2019,24.156696,53.200000,63.482143,10.227679,3.0
35,CABA,2,2020,24.108621,59.600000,64.150862,11.556034,911.0
36,CABA,3,2018,22.034274,81.000000,63.415323,10.028226,38.0
37,CABA,3,2019,20.990323,99.350000,70.350806,10.830645,6.0
38,CABA,3,2020,23.719758,162.300000,73.237903,11.568548,4681.0
39,CABA,4,2018,21.470000,248.200000,79.820833,10.870833,56.0
40,CABA,4,2019,19.290833,42.650000,71.783333,10.079167,12.0
41,CABA,4,2020,17.952500,87.900000,74.383333,10.450000,2816.0
42,CABA,5,2018,16.365323,200.950000,80.221774,9.221774,6.0
43,CABA,5,2019,15.872177,81.400000,75.842742,10.701613,2.0
44,CABA,5,2020,15.230242,15.250000,71.870968,10.141129,594.0
45,CABA,6,2018,10.795833,9.800000,73.858333,8.850000,1.0
46,CABA,6,2019,14.474583,191.750000,79.587500,9.908333,1.0
47,CABA,6,2020,12.650417,76.800000,78.812500,9.691667,8.0
48,CABA,7,2018,10.673790,119.800000,80.822581,11.487903,0.0
49,CABA,7,2019,11.476210,91.750000,74.298387,8.887097,0.0

In [38]:
casos.cantidad_casos=casos.cantidad_casos.astype(int)

In [39]:
casos.head(50)

,PROVINCIA,MES,AÑO,TEMPERATURA (ºC),PRECIPITACION (mm),HR (%),INTENSIDAD DE VIENTO (km/h),cantidad_casos
0,BUENOS AIRES,1,2018,23.818903,78.826000,59.146452,14.287097,0
1,BUENOS AIRES,1,2019,22.901084,131.553399,69.955962,14.790099,0
2,BUENOS AIRES,1,2020,22.715584,79.471401,62.084416,15.177807,103
3,BUENOS AIRES,2,2018,23.143357,49.372000,62.202143,13.391429,9
4,BUENOS AIRES,2,2019,21.580357,60.700000,66.137143,12.844286,7
5,BUENOS AIRES,2,2020,21.921123,87.724632,66.459270,14.743680,426
6,BUENOS AIRES,3,2018,19.504000,69.082000,64.185161,13.586452,70
7,BUENOS AIRES,3,2019,18.507166,99.188702,74.474500,13.205939,30
8,BUENOS AIRES,3,2020,21.853557,155.041634,73.155468,13.345191,2377
9,BUENOS AIRES,4,2018,18.621348,141.735824,78.769179,12.490994,59
10,BUENOS AIRES,4,2019,16.302600,44.530000,73.969333,11.300000,12
11,BUENOS AIRES,4,2020,15.744112,107.766712,76.163376,13.279101,1319
12,BUENOS AIRES,5,2018,13.449032,117.732000,83.012258,11.156774,15
13,BUENOS AIRES,5,2019,12.482000,54.382000,79.051613,12.054839,3
14,BUENOS AIRES,5,2020,12.536700,17.883718,76.064069,14.178878,338
15,BUENOS AIRES,6,2018,8.231733,13.326000,75.712667,12.865333,0
16,BUENOS AIRES,6,2019,11.143667,102.586000,81.225333,13.998000,0
17,BUENOS AIRES,6,2020,9.753102,63.969393,80.034106,12.358555,11
18,BUENOS AIRES,7,2018,8.098323,67.104000,82.154839,13.823871,0
19,BUENOS AIRES,7,2019,8.322754,34.790821,76.181759,11.975436,0
20,BUENOS AIRES,8,2018,9.790645,38.502000,74.400645,15.110968,0
21,BUENOS AIRES,8,2019,9.667311,13.834558,68.372018,13.231464,0
22,BUENOS AIRES,9,2018,14.295133,107.376000,75.001333,14.029333,0
23,BUENOS AIRES,9,2019,12.372933,29.706000,63.532000,15.346667,0
24,BUENOS AIRES,10,2018,15.258870,44.204074,69.678055,14.205650,0
25,BUENOS AIRES,10,2019,15.241742,112.102000,67.305806,15.910323,0
26,BUENOS AIRES,11,2018,18.957123,139.897751,68.382413,15.964554,0
27,BUENOS AIRES,11,2019,20.204733,55.152000,62.044667,15.905333,0
28,BUENOS AIRES,12,2018,21.134901,142.385242,63.023179,15.547981,0
29,BUENOS AIRES,12,2019,21.684645,88.658000,58.165161,15.627097,0
30,CABA,1,2018,25.350806,35.300000,61.604839,12.500000,0
31,CABA,1,2019,24.774194,145.750000,70.608871,11.963710,2
32,CABA,1,2020,24.758468,66.150000,61.419355,12.153226,162
33,CABA,2,2018,24.606250,42.150000,63.611607,12.486607,10
34,CABA,2,2019,24.156696,53.200000,63.482143,10.227679,3
35,CABA,2,2020,24.108621,59.600000,64.150862,11.556034,911
36,CABA,3,2018,22.034274,81.000000,63.415323,10.028226,38
37,CABA,3,2019,20.990323,99.350000,70.350806,10.830645,6
38,CABA,3,2020,23.719758,162.300000,73.237903,11.568548,4681
39,CABA,4,2018,21.470000,248.200000,79.820833,10.870833,56
40,CABA,4,2019,19.290833,42.650000,71.783333,10.079167,12
41,CABA,4,2020,17.952500,87.900000,74.383333,10.450000,2816
42,CABA,5,2018,16.365323,200.950000,80.221774,9.221774,6
43,CABA,5,2019,15.872177,81.400000,75.842742,10.701613,2
44,CABA,5,2020,15.230242,15.250000,71.870968,10.141129,594
45,CABA,6,2018,10.795833,9.800000,73.858333,8.850000,1
46,CABA,6,2019,14.474583,191.750000,79.587500,9.908333,1
47,CABA,6,2020,12.650417,76.800000,78.812500,9.691667,8
48,CABA,7,2018,10.673790,119.800000,80.822581,11.487903,0
49,CABA,7,2019,11.476210,91.750000,74.298387,8.887097,0

In [40]:
np.shape(casos)
print(f'Nuestro dataset luego de la limpieza tiene {casos.shape[0]} filas y {clima.shape[1]} columnas.')

Nuestro dataset luego de la limpieza tiene 750 filas y 6 columnas.

In [41]:
#Modificamos finalmente los nombres de nuestras columnas para trabajar luego en el EDA
casos.rename(columns={'PROVINCIA':'Provincia'}, inplace=True)
casos.rename(columns={'MES':'Mes'}, inplace=True)
casos.rename(columns={'AÑO':'Anio'}, inplace=True)
casos.rename(columns={'TEMPERATURA (ºC)':'Temperatura'}, inplace=True)
casos.rename(columns={'PRECIPITACION (mm)':'Precipitacion'}, inplace=True)
casos.rename(columns={'HR (%)':'Humedad'}, inplace=True)
casos.rename(columns={'INTENSIDAD DE VIENTO (km/h)':'Vel_vientos'}, inplace=True)
casos

,Provincia,Mes,Anio,Temperatura,Precipitacion,Humedad,Vel_vientos,cantidad_casos
0,BUENOS AIRES,1,2018,23.818903,78.826000,59.146452,14.287097,0
1,BUENOS AIRES,1,2019,22.901084,131.553399,69.955962,14.790099,0
2,BUENOS AIRES,1,2020,22.715584,79.471401,62.084416,15.177807,103
3,BUENOS AIRES,2,2018,23.143357,49.372000,62.202143,13.391429,9
4,BUENOS AIRES,2,2019,21.580357,60.700000,66.137143,12.844286,7
...,...,...,...,...,...,...,...,...
745,USHUAIA,10,2019,6.205645,47.900000,66.177419,28.225806,0
746,USHUAIA,11,2018,8.048333,23.500000,61.933333,30.483333,0
747,USHUAIA,11,2019,7.395833,50.100000,71.591667,22.641667,0
748,USHUAIA,12,2018,9.560484,24.200000,63.362903,25.620968,0
749,USHUAIA,12,2019,9.342742,39.800000,67.120968,25.290323,0

# EXPORTAR DATAFRAME

In [42]:
#Guardamos nuestro dataframe en CSV en local.
casos.to_csv("Casos_Dengue_Procesados.csv", index=False)